snowflake:
  stage_fqn: "SC_RAW_DATA.CSV_STAGE"
  table_fqn: "SC_RAW_DATA.raw_data"
  postgre_table: "SC_RAW_DATA.RAW_DATA_POSTGRE"


# PostgreSQL configuration
postgresql:
  schema: "staging"
  table: "hospital_transactions"

paths:
  data_dir: "data/external"
  cleaned_dataset: "dataset_clean.csv"
  batch_dataset: "heart_2020_cleaned.csv"

# Column definitions
columns:
  hospital_transaction:
    - "transaction_id"
    - "patient_id"
    - "admission_id"
    - "department"
    - "doctor"
    - "service"
    - "cost"
    - "payment_method"
    - "transaction_time"
    - "status"
    - "ingested_at"

  heart_disease:
    - "HeartDisease"
    - "BMI"
    - "Smoking"
    - "AlcoholDrinking"
    - "Stroke"
    - "PhysicalHealth"
    - "MentalHealth"
    - "DiffWalking"
    - "Sex"
    - "AgeCategory"
    - "Race"
    - "Diabetic"
    - "PhysicalActivity"
    - "GenHealth"
    - "SleepTime"
    - "Asthma"
    - "KidneyDisease"
    - "SkinCancer"

