{{ config(
    materialized='table',
    schema='sc_analytics',) }}

with date_spine as (
    select dateadd('day', seq4(), '2000-01-01'::date) as date_value
    from table(generator(rowcount => 36525)) -- ~100 years; adjust as needed
),

date_attributes as (
    select
        date_value,
        -- Date components
        year(date_value) as year,
        month(date_value) as month,
        day(date_value) as day,
        dayofweek(date_value) as day_of_week,
        dayofyear(date_value) as day_of_year,
        -- Fiscal periods
        quarter(date_value) as quarter,
        case
            when month(date_value) in (1, 2, 3) then 'Q1'
            when month(date_value) in (4, 5, 6) then 'Q2'
            when month(date_value) in (7, 8, 9) then 'Q3'
            else 'Q4'
        end as fiscal_quarter,
        -- Business logic
        coalesce(dayofweekiso(date_value) in (6, 7), false) as is_weekend,
        coalesce(date_value = current_date(), false) as is_today
    from date_spine
    where date_value <= current_date()
)

select
    -- surrogate generated by dbt_utils (stable hash based on date_value)
    {{ dbt_utils.generate_surrogate_key(['date_value']) }} as date_key,
    date_value,
    year,
    month,
    day,
    day_of_week,
    day_of_year,
    quarter,
    fiscal_quarter,
    is_weekend,
    is_today
from date_attributes
